version: '3.7'

services: 
  chatbot:
      image: diendh/chatbot
      container_name: chatbot
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./.env
      ports:
        - 3002:3002
